# Generated by Django 4.1.13 on 2024-03-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('flags', models.IntegerField(default=0)),
                ('observed_time_unix_nano', models.BigIntegerField(default=0)),
                ('severity_number', models.IntegerField(default=0)),
                ('severity_text', models.CharField(default='', max_length=50)),
                ('span_id', models.CharField(blank=True, max_length=255)),
                ('time_unix_nano', models.BigIntegerField(default=0)),
                ('trace_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
